name: 'Publish Release'

on:
  push:
    tags:
      - '*'

env:
  EXIT_ON_PUBLISH_FAILURE: 1

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: write
      discussions: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867  # v7.1.6
        with:
          enable-cache: true
          python-version-file: .python-version

      - name: Verify Versions Match
        run: |
          TAG_VERSION=$(git describe HEAD --tags --abbrev=0)
          MODULE_VERSION=$(uv version)
          echo "Git Tag Version: $TAG_VERSION"
          echo "Python Module Version: $MODULE_VERSION"
          if [[ "wols $TAG_VERSION" != "$MODULE_VERSION" ]]; then exit 1; fi
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Build Package
        run: uv build

      - name: Publish to PyPi
        run: uv publish || exit $EXIT_ON_PUBLISH_FAILURE

      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b  # v2.5.0
        with:
          discussion_category_name: announcements
          generate_release_notes: true
          files: |
            dist/wols-${{env.TAG_VERSION}}.tar.gz
            dist/wols-${{env.TAG_VERSION}}-py3-none-any.whl
